### ISSUE TITLE
Pom/nexus not working?

### ISSUE THREAD

**Issue by PiggyPiglet** [domisum/CompitumLib#1]
Hey, I'm trying to use this api in a plugin of mine, but I can't compile it since your pom seems to not be picking up your dependencies from the repo's. I have no clue why. Intellij isn't giving me any errors, it's simply just not giving me any of the dependencies, apart from lombok and particlelib.

**Comment by domisum** [comment]
Thank you for pointing that out. I have added the repositories to the project pom.xml (the repositories were specified in my settings.xml). 

Have a look if it now works for you.

**Comment by PiggyPiglet** [comment]
Thanks, that fixed it. I just had to add the spigot repo and comment out the craftbukkit dependency. I've compiled it now, but haven't tested it yet. I'll most likely definitely be needing your help soon, I really look forward to using this api. Do you have discord? Or any faster methods of communications, since github issues definitely isn't what I'd call a good communication service.

**Comment by domisum** [comment]
Yes, you can add me on Discord: domisum#3116
