### ISSUE TITLE
Pathfinding bug?

### ISSUE THREAD

**Issue by ghost** [domisum/CompitumLib#2]
I am using this lib on 1.12.2 for pathfinding, however it has very weird behavior, sometimes when you choose to pathfind to location, it visits maximum nodes (even after increasing the limit to insane number) without finding a path, while when you choose a block next to the failed location, it finds path pretty quickly, even if it is flat area, I think it should be more consistent considering there are no additional obstacles in reaching this block

**Comment by domisum** [comment]
Hi,
this code is pretty old and I no longer actively work on it. 
This means I can't help you with this, sorry.
